#    / \  | | __ _  ___ _ __(_) |_| |_ _   _
#   / _ \ | |/ _` |/ __| '__| | __| __| | | |
#  / ___ \| | (_| | (__| |  | | |_| |_| |_| |
# /_/   \_\_|\__,_|\___|_|  |_|\__|\__|\__, |
# By Jerrod Havig 2024-06-06           |___/
# $HOME/.config/alacritty/alacritty.toml

[ env ]

TERM = "xterm-256color"

[ window ]
title = "Alacritty"
decorations = "none"
blur = true
opacity = 0.9
padding.x = 6
padding.y = 3

[ font ]

normal.family = "GeistMonoNerdFont"
bold.family = "GeistMonoNerdFont"
italic.family = "GeistMonoNerdFont"
bold_italic.family = "GeistMonoNerdFont"

size = 8.0

[ cursor ]

unfocused_hollow = true

[ scrolling ]

history = 2000

[general]

live_config_reload = true

# Themes --
import = [
	#"~/.config/alacritty/themes/gruvbox_material_medium_dark.toml"
	#"~/.config/alacritty/themes/catppuccin-mocha.toml"
	#"~/.config/alacritty/themes/aura-theme.toml"
	#"~/.config/alacritty/themes/dracula.toml"
	"~/.config/alacritty/themes/rose-pine.toml"
]
